/**
 * Generates src/pipeline/osm/implicit-speeds.generated.ts from the OSM wiki's "Default speed limits" table
 * as published by https://github.com/westnordost/osm-legal-default-speeds (`legal_default_speeds.json`;
 * code BSD-3-Clause, data CC BY-SA 2.0 like the wiki page it is generated from).
 *
 *   npx tsx scripts/generate-implicit-speeds.mts <path-to-legal_default_speeds.json>
 *
 * Which implicit values (`maxspeed:type=CC:urban` etc.) may be resolved to a number is a safety decision, not a
 * convenience — a wrong number in front of a driver is worse than no number (docs/europe-feasibility.md §6):
 *
 *   1. Only the plain road types "urban" and "rural" are resolved, and only where the country's entry is a plain
 *      number (or "NN mph"), not a conditional or non-numeric value.
 *   2. A country is skipped for a base type if ANY refinement of that base type in the same country carries a
 *      different value (e.g. FR "rural" 80 vs "rural road with 2 or more lanes in each direction" 90; ES "urban"
 *      30 vs the 20/50 sub-types). Such a tag does not say which sub-type the road is, so any single number
 *      would be wrong on part of the ways.
 *   3. Nothing else is resolved here (motorway, living_street, GB nsl_* — no blanket numeric limit, or the tag
 *      is not evidenced by the dataset). `zoneNN` is handled by pattern in normalize.ts (the number is in the tag).
 */
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

interface Entry {
  name?: string;
  tags?: Record<string, string>;
}

interface Dataset {
  meta: { license: string; licenseUrl: string; revisionId: string; source: string; timestamp: string };
  speedLimitsByCountryCode: Record<string, Entry[]>;
}

const input = process.argv[2];
if (!input) {
  console.error("usage: npx tsx scripts/generate-implicit-speeds.mts <path-to-legal_default_speeds.json>");
  process.exit(1);
}

const dataset = JSON.parse(readFileSync(input, "utf8")) as Dataset;
const PLAIN = /^(\d+)(?: (mph))?$/;

const resolved: Record<string, { value: number; unit: "kmh" | "mph" }> = {};
const ambiguous: string[] = [];
const mphCountries = new Set<string>();

for (const [countryCode, entries] of Object.entries(dataset.speedLimitsByCountryCode)) {
  for (const entry of entries) {
    if (entry.tags?.maxspeed?.endsWith(" mph")) mphCountries.add(countryCode);
  }
  for (const base of ["urban", "rural"] as const) {
    const exact = entries.find((entry) => entry.name === base);
    const match = exact?.tags?.maxspeed ? PLAIN.exec(exact.tags.maxspeed) : null;
    if (!exact || !match) continue;
    const conflicting = entries.filter((entry) => entry.name?.startsWith(`${base} `) && entry.tags?.maxspeed !== undefined && entry.tags.maxspeed !== exact.tags!.maxspeed);
    if (conflicting.length > 0) {
      ambiguous.push(`${countryCode}:${base} (${exact.tags!.maxspeed}) conflicts with ${conflicting.map((entry) => `${entry.name}=${entry.tags!.maxspeed}`).join(", ")}`);
      continue;
    }
    resolved[`${countryCode}:${base}`] = { value: Number(match[1]), unit: match[2] ? "mph" : "kmh" };
  }
}

const keys = Object.keys(resolved).sort();
const lines: string[] = [];
lines.push("// GENERATED by scripts/generate-implicit-speeds.mts — do not edit by hand; re-run the script to update.");
lines.push("//");
lines.push("// Source: OSM wiki \"Default speed limits\" as published by github.com/westnordost/osm-legal-default-speeds");
lines.push(`// (data ${dataset.meta.license}, ${dataset.meta.licenseUrl}; generator code BSD-3-Clause).`);
lines.push(`// Wiki revision ${dataset.meta.revisionId} of ${dataset.meta.timestamp}.`);
lines.push("// Attribution: © OpenStreetMap contributors (wiki content), CC BY-SA 2.0.");
lines.push("");
lines.push("export const IMPLICIT_SPEEDS_SOURCE = {");
lines.push('  dataset: "westnordost/osm-legal-default-speeds",');
lines.push(`  wikiPage: ${JSON.stringify(dataset.meta.source)},`);
lines.push(`  wikiRevision: ${JSON.stringify(dataset.meta.revisionId)},`);
lines.push(`  wikiTimestamp: ${JSON.stringify(dataset.meta.timestamp)},`);
lines.push(`  license: ${JSON.stringify(dataset.meta.license)},`);
lines.push("} as const;");
lines.push("");
lines.push("/** `maxspeed:type` values (\"CC:urban\" / \"CC:rural\") that resolve to one unambiguous number. */");
lines.push('export const IMPLICIT_MAXSPEED: Readonly<Record<string, { value: number; unit: "kmh" | "mph" }>> = {');
for (const key of keys) lines.push(`  ${JSON.stringify(key)}: { value: ${resolved[key]!.value}, unit: "${resolved[key]!.unit}" },`);
lines.push("};");
lines.push("");
lines.push("/** Countries/regions whose signed limits are in mph — `zoneNN` is never read as km/h there. */");
lines.push(`export const MPH_COUNTRIES: ReadonlySet<string> = new Set(${JSON.stringify([...mphCountries].sort())});`);
lines.push("");

const outPath = path.resolve(fileURLToPath(import.meta.url), "../../src/pipeline/osm/implicit-speeds.generated.ts");
writeFileSync(outPath, lines.join("\n"));
console.log(`wrote ${outPath}: ${keys.length} resolved country/type pairs, ${ambiguous.length} omitted as ambiguous:`);
for (const line of ambiguous) console.log(`  - ${line}`);
