// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `open`, `runtime`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `DartSecureStore`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `delete`, `drop`, `fmt`, `from`, `get`, `set`

/// The library's version.
String libraryVersion() => RustLib.instance.api.crateApiClientLibraryVersion();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<NativeClient>>
abstract class NativeClient implements RustOpaqueInterface {
  /// Runs one API method (`api.md` lists them) and returns its result as
  /// JSON: `{"ok": …}` or `{"error": {"code": …, "message": …}}`.
  /// `args_json` may be empty for a method without arguments.
  Future<String> call({required String method, required String argsJson});

  /// `options_json` is the client's options (`api.md`, "Options") plus
  /// `storagePath`, the directory the database and the secrets go in. The
  /// device's secrets go into a file in that directory (readable by the
  /// current user only — not hardware-backed); see
  /// [`create_with_secure_store`](Self::create_with_secure_store) for the
  /// platform's own store.
  static Future<NativeClient> create({required String optionsJson}) =>
      RustLib.instance.api
          .crateApiClientNativeClientCreate(optionsJson: optionsJson);

  /// [`create`](Self::create) with the device's secrets kept in the host's
  /// own store (Keychain, Keystore, ...) instead of a file: `get` answers
  /// the value under a key (`null` if there is none), `set` and `delete`
  /// answer whether they worked.
  static Future<NativeClient> createWithSecureStore(
          {required String optionsJson,
          required FutureOr<String?> Function(String) get_,
          required FutureOr<bool> Function(String, String) set_,
          required FutureOr<bool> Function(String) delete}) =>
      RustLib.instance.api.crateApiClientNativeClientCreateWithSecureStore(
          optionsJson: optionsJson, get_: get_, set_: set_, delete: delete);

  /// Every event as it happens (`api.md`, "Events"; they are also queued for
  /// `pollEvents`), as JSON — a `Stream<String>` in Dart. A second call
  /// replaces the first stream's source.
  Stream<String> events();

  /// Keeps a WebSocket connection to the network open and applies pushed
  /// events (`api.md`, "Realtime push"), on this library's own background
  /// task. Events surface like every other (`pollEvents`, the stream). A
  /// no-op if already running.
  Future<void> startRealtime();

  /// Stops delivering events to the stream.
  Future<void> stopEvents();

  /// Asks a running realtime task to stop — between connection attempts,
  /// not by closing a connection that is open. A no-op if none is running.
  Future<void> stopRealtime();
}

/// Why a client could not be created. Everything after that — every `call` —
/// reports its failures inside the result JSON instead, exactly like the
/// other bindings, so a host handles API errors in one way everywhere.
class ClientError implements FrbException {
  /// One of the API's error codes (`api.md`, "Errors").
  final String errorCode;

  /// A message for the log.
  final String detail;

  const ClientError({
    required this.errorCode,
    required this.detail,
  });

  @override
  int get hashCode => errorCode.hashCode ^ detail.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClientError &&
          runtimeType == other.runtimeType &&
          errorCode == other.errorCode &&
          detail == other.detail;
}
